import * as THREE from 'three'

// ─── Unity C# ────────────────────────────────────────────────────────────────
export function exportUnityCS(voxels) {
  const lines = [
    'using UnityEngine;',
    '',
    'public class VoxelMap : MonoBehaviour',
    '{',
    '    public GameObject voxelPrefab;',
    '',
    '    void Start()',
    '    {',
    '        SpawnVoxels();',
    '    }',
    '',
    '    void SpawnVoxels()',
    '    {',
  ]

  voxels.forEach(({ position: [x, y, z], color }) => {
    const c = new THREE.Color(color)
    const r = c.r.toFixed(3)
    const g = c.g.toFixed(3)
    const b = c.b.toFixed(3)
    lines.push(
      `        SpawnAt(new Vector3(${x}f, ${y}f, ${z}f), new Color(${r}f, ${g}f, ${b}f));`
    )
  })

  lines.push(
    '    }',
    '',
    '    void SpawnAt(Vector3 pos, Color color)',
    '    {',
    '        var go = Instantiate(voxelPrefab, pos, Quaternion.identity, transform);',
    '        var renderer = go.GetComponent<Renderer>();',
    '        if (renderer) renderer.material.color = color;',
    '    }',
    '}',
  )

  downloadText(lines.join('\n'), 'VoxelMap.cs')
}

// ─── Godot GDScript ───────────────────────────────────────────────────────────
export function exportGodotGD(voxels) {
  const lines = [
    'extends GridMap',
    '',
    '# Auto-generated by SpriteForge Voxel Editor',
    '# Attach this script to a GridMap node.',
    '# Make sure your MeshLibrary has an item with id 0.',
    '',
    'func _ready():',
    '    _build_map()',
    '',
    'func _build_map():',
    '    var cells = {',
  ]

  voxels.forEach(({ position: [x, y, z] }, i) => {
    const comma = i < voxels.length - 1 ? ',' : ''
    lines.push(`        Vector3i(${x}, ${y}, ${z}): 0${comma}`)
  })

  lines.push(
    '    }',
    '    for cell in cells:',
    '        set_cell_item(cell, cells[cell])',
  )

  downloadText(lines.join('\n'), 'VoxelMap.gd')
}

// ─── GLTF ────────────────────────────────────────────────────────────────────
export async function exportGLTF(voxels) {
  const { GLTFExporter } = await import('three/examples/jsm/exporters/GLTFExporter.js')
  const group = new THREE.Group()
  const geo = new THREE.BoxGeometry(1, 1, 1)

  // Group voxels by color to reduce object count
  const byColor = {}
  voxels.forEach(({ position, color }) => {
    if (!byColor[color]) byColor[color] = []
    byColor[color].push(position)
  })

  Object.entries(byColor).forEach(([color, positions]) => {
    const mat = new THREE.MeshStandardMaterial({ color })
    positions.forEach(([x, y, z]) => {
      const mesh = new THREE.Mesh(geo, mat)
      mesh.position.set(x, y, z)
      group.add(mesh)
    })
  })

  const exporter = new GLTFExporter()
  const gltfData = await new Promise((resolve, reject) => {
    exporter.parse(group, resolve, reject, { binary: false })
  })

  const json = JSON.stringify(gltfData, null, 2)
  downloadText(json, 'voxel_model.gltf')

  // Dispose
  geo.dispose()
  Object.values(byColor).forEach((_, i) => {
    // mat is reused per color group — dispose is handled by GC
  })
}

// ─── Helper ───────────────────────────────────────────────────────────────────
function downloadText(content, filename) {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
